In [6]:
class Employee:

    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    @classmethod
    def average_salary(cls, employees):
        total_salary = sum(employee.salary for employee in employees)
        return total_salary / cls.employee_count if cls.employee_count > 0 else 0

    @staticmethod
    def employee_info(employee):
        return f"Name: {employee.name}, Family: {employee.family}, Salary: {employee.salary}, Department: {employee.department}"


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, benefits):
        super().__init__(name, family, salary, department)
        self.benefits = benefits

    def fulltime_employee_info(self):
        return f"{super().employee_info(self)}, Benefits: {self.benefits}"


emp1 = Employee("Mahesh", "Babu", 45000, "Civil")
emp2 = Employee("Sampoornesh", "Babu", 56000, "Cse")
emp3 = FulltimeEmployee("Ayyagare", "Number1", 90000, "Hardware", "Automobile")

employees = [emp1, emp2, emp3]


print(Employee.employee_info(emp1))
print(Employee.employee_info(emp2))
print(emp3.fulltime_employee_info())

Name: Mahesh, Family: Babu, Salary: 45000, Department: Civil
Name: Sampoornesh, Family: Babu, Salary: 56000, Department: Cse
Name: Ayyagare, Family: Number1, Salary: 90000, Department: Hardware, Benefits: Automobile


In [8]:
import numpy as np

vector = np.random.uniform(1, 20, size=20)

array = vector.reshape(4, 5)

mask = array == np.max(array, axis=1, keepdims=True)

array[mask] = 0

print("The output would be: ")
print(array)

The output would be: 
[[ 8.69983979  6.66565386 11.75313915  0.          3.07396368]
 [ 0.          7.79966242 14.10309298  1.78864059  5.62218557]
 [ 0.          1.6576157   5.55752191 13.23542458  7.17811986]
 [15.22991232 16.75295173  0.          1.66732371 13.90922045]]
